name: 'Rust Release'

on:
  push:
    branches:
      - release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      # - name: Run tests
      #   run: cargo test

  build:
    name: Build
    needs: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: release-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: release-windows.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: release-macos
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: release-macos-aarch64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifacts
        shell: bash
        run: |
          # 各プラットフォーム用にディレクトリを作成
          mkdir -p artifacts/${{ matrix.artifact_name }}
          
          # バイナリをディレクトリ内にコピー
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/*.exe artifacts/${{ matrix.artifact_name }}/
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            # macOS用のfindコマンド (BSD find)
            find target/${{ matrix.target }}/release -type f -perm +111 -not -path "*/\.*" -not -path "*/deps/*" -not -path "*/examples/*" -not -path "*/incremental/*" -exec cp {} artifacts/${{ matrix.artifact_name }}/ \;
          else
            # Linux用のfindコマンド (GNU find)
            find target/${{ matrix.target }}/release -type f -executable -not -path "*/\.*" -not -path "*/deps/*" -not -path "*/examples/*" -not -path "*/incremental/*" -exec cp {} artifacts/${{ matrix.artifact_name }}/ \;
          fi
          
          # リソースディレクトリのコピー
          if [ -d "resource" ]; then
            mkdir -p artifacts/${{ matrix.artifact_name }}/resource
            cp -r resource/* artifacts/${{ matrix.artifact_name }}/resource/
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: artifacts/${{ matrix.artifact_name }}
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate release name
        run: |
          DATE=$(date +'%Y%m%d')
          HASH=$(git rev-parse --short HEAD)
          echo "RELEASE_NAME=release-${DATE}-${HASH}" >> $GITHUB_ENV
          echo "RELEASE_TITLE=Release ${DATE} (${HASH})" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
            sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
            sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh


      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ env.RELEASE_NAME }}" \
            --title "${{ env.RELEASE_TITLE }}" \
            --notes "Auto-generated release from release branch commit ${GITHUB_SHA}" \
            --target "$GITHUB_REF_NAME"

          # アップロード対象ファイル一覧を出力
          find artifacts -type f | sort

          # 個別にファイルをアップロード（ディレクトリ名＝artifact_nameを付ける）
          find artifacts -type f | while read file; do
            artifact_dir="$(basename "$(dirname "$file")")"
            filename="$(basename "$file")"
            gh release upload "${{ env.RELEASE_NAME }}" "$file" \
              --clobber \
              --name "${artifact_dir}-${filename}"
          done